server:
  port: 8888
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
    internal_proxies: 10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|169\.254\.\d{1,3}\.\d{1,3}|127\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}|172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}|172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}
spring:
  thymeleaf:
    cache: false
security:
  ignored: /favicon.ico, /, /authorization_code
  basic:
    enabled: false
logging.level:
  org.springframework.security: DEBUG
resourceServerUrl: ${RESOURCE_URL:https://resource-server.domain}